@echo off
echo Staging changes...
git add .
echo Committing changes...
git commit -m "feat: Implement full Export Service (backend & frontend) w/ GEE integration"
echo Pushing to remote...
git push
echo Deployment complete.
